version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sunska-db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  app:
    build: .
    container_name: node_app
    environment:
      DATABASE_URL: mysql://user:root@db:3306/sunska-db
      JWT_SECRET: your_jwt_secret
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
